import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

function HomeSection3() {
  useEffect(() => {
    AOS.init({
      duration: 700,
      debounceDelay: 50,
      mirror: true,
      easing: "ease-out-cubic",
    });
  }, []);

  return (
    <>
      <div
        className="font-manrope mt-[5rem] flex flex-col md:flex-row text-white justify-center items-center gap-5 md:gap-[6rem] py-[3rem] p-10 mx-[5rem] rounded-br-[6rem] 2xl:rounded-br-[12rem] rounded-bl-3xl rounded-tl-3xl rounded-tr-3xl bg-gradient-to-r from-secondaryColor_darkPurple to-primaryColor_turquoise"
        data-aos="fade-left"
      >
        <p className="font-bold px-0 mobile:px-6 md:px-0 text-[1.5rem]">
          “ Creativity can be nurtured, but not be generated by AI ”
        </p>
        <h3 className="font-clashDisplay text-[2rem]">- Slove</h3>
      </div>
    </>
  );
}

export default HomeSection3;
